### ISSUE TITLE
Error installing dependencies

### ISSUE THREAD

**Issue by GerardBarriga** [Sklyvan/ScrapingUPF#1]
En Windows 10 instalando la interfaz gráfica siguiendo los pasos me daba un error `pip install -r GraphicRequirements.txt`  al instalar la última de las dependencias (PyQt5). En mi caso, la solución ha sido cambiar la versión de PyQt5 y ejecutar el comando como administrador. Para ello accedemos al archivo GraphicRequirements que hay en la carpeta de ScrapingUPF y modificamos la penúltima línea PyQt5 == 5.15.4. Cambiamos la versión a la 5.15.5 y guardamos el documento.

**Comment by Sklyvan** [comment]
Gracias por tu comentario, he recibido más de un comentario sobre este problema con PyQt5, así que voy a modificar directamente el archivo de requerimientos.
¡Gracias por tu solución! :)

**Comment by GerardBarriga** [comment]
Nadaaa!
