### ISSUE TITLE
Error al instalar

### ISSUE THREAD

**Issue by danial-im** [Sklyvan/ScrapingUPF#3]
Hago todos los pasos bien hasta que llego al ultimo paso le doy click a "Transferir asignaturas a Google Calendar y entonces la barra carga hasta el 21% y en la terminal me sale que no se puede por KeyError 23954.
![imagen_2023-01-10_163735016](https://user-images.githubusercontent.com/94740373/211594863-c8bba39f-c2b2-4aa2-99ed-2803d6637db6.png)

**Comment by Sklyvan** [comment]
Hola, gracias por tu comentario.
Este error ocurre debido a una pequeña actualización sobre los colores de Google Calendar. He actualizado ya el repositorio. De todas formas, para solucionar tu problema, abre el archivo UserPreferences.ini y reemplaza:
`
SubjectsColors = 5,3
`
Eliminando los números y añadiendo el False.
`
SubjectsColors = False
`
A continuación vuelve a ejecutar el programa.

**Comment by danial-im** [comment]
Gracias
